services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: odis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Infrastructure/Persistence/migrations.sql:/tmp/migrations.sql:ro
volumes:
  pgdata:
