CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE form (
    form_id uuid NOT NULL,
    form_name character varying(20) NOT NULL,
    form_description character varying(100) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_form" PRIMARY KEY (form_id)
);

CREATE TABLE permission (
    permission_id uuid NOT NULL,
    permission_name character varying(20) NOT NULL,
    permission_description character varying(100) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_permission" PRIMARY KEY (permission_id)
);

CREATE TABLE person (
    person_id uuid NOT NULL,
    person_name character varying(15) NOT NULL,
    person_last_name character varying(15) NOT NULL,
    birth_date timestamp with time zone NOT NULL,
    sex text NOT NULL,
    ci character varying(9) NOT NULL,
    email character varying(25),
    phone_number character varying(10) NOT NULL,
    profession character varying(15),
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT person_id PRIMARY KEY (person_id)
);

CREATE TABLE role (
    role_id uuid NOT NULL,
    role_name character varying(20) NOT NULL,
    role_description character varying(100) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_role" PRIMARY KEY (role_id)
);

CREATE TABLE submodule (
    submodule_id integer GENERATED BY DEFAULT AS IDENTITY,
    submodule_name character varying(20) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_submodule" PRIMARY KEY (submodule_id)
);

CREATE TABLE clinic (
    clinic_id uuid NOT NULL,
    clinic_name character varying(20) NOT NULL,
    clinic_address character varying(50) NOT NULL,
    clinic_phone character varying(10) NOT NULL,
    clinic_cell_phone character varying(10) NOT NULL,
    clinic_email character varying(20) NOT NULL,
    logo_ref text,
    logo_url text,
    manager_id uuid NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT clinic_id PRIMARY KEY (clinic_id),
    CONSTRAINT "FK_clinic_person_manager_id" FOREIGN KEY (manager_id) REFERENCES person (person_id) ON DELETE RESTRICT
);

CREATE TABLE patient_responsible (
    patient_responsible_id uuid NOT NULL,
    person_id uuid NOT NULL,
    parentage text NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_patient_responsible" PRIMARY KEY (patient_responsible_id),
    CONSTRAINT "FK_patient_responsible_person_person_id" FOREIGN KEY (person_id) REFERENCES person (person_id) ON DELETE RESTRICT
);

CREATE TABLE "user" (
    user_id uuid NOT NULL,
    person_id uuid NOT NULL,
    password text NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT user_id PRIMARY KEY (user_id),
    CONSTRAINT "FK_user_person_person_id" FOREIGN KEY (person_id) REFERENCES person (person_id) ON DELETE RESTRICT
);

CREATE TABLE role_permission (
    role_permission_id uuid NOT NULL,
    role_id uuid NOT NULL,
    permission_id uuid NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_role_permission" PRIMARY KEY (role_permission_id),
    CONSTRAINT "FK_role_permission_permission_permission_id" FOREIGN KEY (permission_id) REFERENCES permission (permission_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_role_permission_role_role_id" FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE RESTRICT
);

CREATE TABLE form_version (
    form_version_id uuid NOT NULL,
    "SubmodID" integer NOT NULL,
    form_id uuid NOT NULL,
    number_version integer NOT NULL,
    json_schema jsonb NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_form_version" PRIMARY KEY (form_version_id),
    CONSTRAINT "FK_form_version_form_form_id" FOREIGN KEY (form_id) REFERENCES form (form_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_form_version_submodule_SubmodID" FOREIGN KEY ("SubmodID") REFERENCES submodule (submodule_id) ON DELETE RESTRICT
);

CREATE TABLE patient (
    patient_id uuid NOT NULL,
    person_id uuid NOT NULL,
    responsible_id uuid,
    address character varying(50) NOT NULL,
    zone character varying(20) NOT NULL,
    city character varying(20) NOT NULL,
    home_phone character varying(10),
    occupation character varying(15) NOT NULL,
    place_occupation character varying(50) NOT NULL,
    sender character varying(20) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_patient" PRIMARY KEY (patient_id),
    CONSTRAINT "FK_patient_patient_responsible_responsible_id" FOREIGN KEY (responsible_id) REFERENCES patient_responsible (patient_responsible_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_patient_person_person_id" FOREIGN KEY (person_id) REFERENCES person (person_id) ON DELETE RESTRICT
);

CREATE TABLE user_rol (
    user_rol_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_user_rol" PRIMARY KEY (user_rol_id),
    CONSTRAINT "FK_user_rol_role_role_id" FOREIGN KEY (role_id) REFERENCES role (role_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_user_rol_user_user_id" FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
);

CREATE TABLE appointment (
    appointment_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    professional_id uuid NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    appointment_type text NOT NULL,
    reason character varying(100) NOT NULL,
    observations character varying(1000) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_appointment" PRIMARY KEY (appointment_id),
    CONSTRAINT "FK_appointment_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_appointment_user_professional_id" FOREIGN KEY (professional_id) REFERENCES "user" (user_id) ON DELETE RESTRICT
);

CREATE TABLE clinic_history (
    clinic_history_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    submod_id integer NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_clinic_history" PRIMARY KEY (clinic_history_id),
    CONSTRAINT "FK_clinic_history_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_clinic_history_submodule_submod_id" FOREIGN KEY (submod_id) REFERENCES submodule (submodule_id) ON DELETE RESTRICT
);

CREATE TABLE contract (
    contract_id uuid NOT NULL,
    submod_id integer NOT NULL,
    patient_id uuid NOT NULL,
    contract_date timestamp with time zone NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_contract" PRIMARY KEY (contract_id),
    CONSTRAINT "FK_contract_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_contract_submodule_submod_id" FOREIGN KEY (submod_id) REFERENCES submodule (submodule_id) ON DELETE RESTRICT
);

CREATE TABLE form_response (
    form_response_id uuid NOT NULL,
    form_version_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    json_response jsonb NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_form_response" PRIMARY KEY (form_response_id),
    CONSTRAINT "FK_form_response_form_version_form_version_id" FOREIGN KEY (form_version_id) REFERENCES form_version (form_version_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_form_response_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT
);

CREATE TABLE general_history (
    general_history_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    submod_id integer NOT NULL,
    filled_by text NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_general_history" PRIMARY KEY (general_history_id),
    CONSTRAINT "FK_general_history_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_general_history_submodule_submod_id" FOREIGN KEY (submod_id) REFERENCES submodule (submodule_id) ON DELETE RESTRICT
);

CREATE TABLE treatment_summary (
    treatment_summary_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    submod_id integer NOT NULL,
    summary_date timestamp with time zone NOT NULL,
    "State" integer NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedBy" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_treatment_summary" PRIMARY KEY (treatment_summary_id),
    CONSTRAINT "FK_treatment_summary_patient_patient_id" FOREIGN KEY (patient_id) REFERENCES patient (patient_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_treatment_summary_submodule_submod_id" FOREIGN KEY (submod_id) REFERENCES submodule (submodule_id) ON DELETE RESTRICT
);

CREATE TABLE monitoring (
    monitoring_id uuid NOT NULL,
    appointment_id uuid NOT NULL,
    nomenclature character varying(10) NOT NULL,
    treatment character varying(50) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_monitoring" PRIMARY KEY (monitoring_id),
    CONSTRAINT "FK_monitoring_appointment_appointment_id" FOREIGN KEY (appointment_id) REFERENCES appointment (appointment_id) ON DELETE RESTRICT
);

CREATE TABLE payment_manager (
    payment_manager_id uuid NOT NULL,
    person_id uuid NOT NULL,
    contract_id uuid NOT NULL,
    parentage character varying(20) NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_payment_manager" PRIMARY KEY (payment_manager_id),
    CONSTRAINT "FK_payment_manager_contract_contract_id" FOREIGN KEY (contract_id) REFERENCES contract (contract_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_payment_manager_person_person_id" FOREIGN KEY (person_id) REFERENCES person (person_id) ON DELETE RESTRICT
);

CREATE TABLE pretreatment_exam (
    pretreatment_exam_id uuid NOT NULL,
    history_id uuid NOT NULL,
    observations character varying(200) NOT NULL,
    interconsultation character varying(1000) NOT NULL,
    piece character varying(18) NOT NULL,
    caries character varying(20),
    treatment character varying(50),
    cost integer NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_pretreatment_exam" PRIMARY KEY (pretreatment_exam_id),
    CONSTRAINT "FK_pretreatment_exam_general_history_history_id" FOREIGN KEY (history_id) REFERENCES general_history (general_history_id) ON DELETE RESTRICT
);

CREATE TABLE evidence_file (
    evidence_file_id uuid NOT NULL,
    monitoring_id uuid NOT NULL,
    file_type text NOT NULL,
    external_reference character varying(200),
    reference character varying(200),
    description character varying(200),
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_evidence_file" PRIMARY KEY (evidence_file_id),
    CONSTRAINT "FK_evidence_file_monitoring_monitoring_id" FOREIGN KEY (monitoring_id) REFERENCES monitoring (monitoring_id) ON DELETE RESTRICT
);

CREATE TABLE treatment_progress (
    treatment_progress_id uuid NOT NULL,
    exam_id uuid NOT NULL,
    payment integer NOT NULL,
    debt integer NOT NULL,
    state text NOT NULL,
    created_by text NOT NULL,
    updated_by text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_treatment_progress" PRIMARY KEY (treatment_progress_id),
    CONSTRAINT "FK_treatment_progress_pretreatment_exam_exam_id" FOREIGN KEY (exam_id) REFERENCES pretreatment_exam (pretreatment_exam_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_appointment_patient_id" ON appointment (patient_id);

CREATE INDEX "IX_appointment_professional_id" ON appointment (professional_id);

CREATE UNIQUE INDEX "IX_clinic_manager_id" ON clinic (manager_id);

CREATE INDEX "IX_clinic_history_patient_id" ON clinic_history (patient_id);

CREATE UNIQUE INDEX "IX_clinic_history_submod_id" ON clinic_history (submod_id);

CREATE INDEX "IX_contract_patient_id" ON contract (patient_id);

CREATE UNIQUE INDEX "IX_contract_submod_id" ON contract (submod_id);

CREATE INDEX "IX_evidence_file_monitoring_id" ON evidence_file (monitoring_id);

CREATE INDEX "IX_form_response_form_version_id" ON form_response (form_version_id);

CREATE INDEX "IX_form_response_patient_id" ON form_response (patient_id);

CREATE INDEX "IX_form_version_form_id" ON form_version (form_id);

CREATE INDEX "IX_form_version_SubmodID" ON form_version ("SubmodID");

CREATE INDEX "IX_general_history_patient_id" ON general_history (patient_id);

CREATE UNIQUE INDEX "IX_general_history_submod_id" ON general_history (submod_id);

CREATE UNIQUE INDEX "IX_monitoring_appointment_id" ON monitoring (appointment_id);

CREATE UNIQUE INDEX "IX_patient_person_id" ON patient (person_id);

CREATE UNIQUE INDEX "IX_patient_responsible_id" ON patient (responsible_id);

CREATE UNIQUE INDEX "IX_patient_responsible_person_id" ON patient_responsible (person_id);

CREATE INDEX "IX_payment_manager_contract_id" ON payment_manager (contract_id);

CREATE UNIQUE INDEX "IX_payment_manager_person_id" ON payment_manager (person_id);

CREATE UNIQUE INDEX "IX_pretreatment_exam_history_id" ON pretreatment_exam (history_id);

CREATE INDEX "IX_role_permission_permission_id" ON role_permission (permission_id);

CREATE INDEX "IX_role_permission_role_id" ON role_permission (role_id);

CREATE INDEX "IX_treatment_progress_exam_id" ON treatment_progress (exam_id);

CREATE UNIQUE INDEX "IX_treatment_summary_patient_id" ON treatment_summary (patient_id);

CREATE UNIQUE INDEX "IX_treatment_summary_submod_id" ON treatment_summary (submod_id);

CREATE UNIQUE INDEX "IX_user_person_id" ON "user" (person_id);

CREATE INDEX "IX_user_rol_role_id" ON user_rol (role_id);

CREATE INDEX "IX_user_rol_user_id" ON user_rol (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250930234315_30sep', '9.0.9');

COMMIT;

